import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { loadModel, readSystemPrompt } from './registry.js';
import { listPairs } from './pairs.js';
import { sha256File } from './status.js';

export interface BuildOptions {
  examples?: number;
  baseModel?: string;
}

export interface BuildResult {
  modelfilePath: string;
  buildDir: string;
  baseModel: string;
  exampleCount: number;
  totalPairs: number;
  systemPromptIncluded: boolean;
  ollamaTag: string;
  createCommand: string;
}

const DEFAULT_BASE = 'qwen2.5:1.5b';
const DEFAULT_EXAMPLES = 4;

function escapeTriple(text: string): string {
  return text.replace(/"""/g, '\\"\\"\\"');
}

export async function buildModelfile(
  name: string,
  opts: BuildOptions = {}
): Promise<BuildResult> {
  const model = await loadModel(name);
  if (!model) throw new Error(`model not found: ${name}`);

  const system = (await readSystemPrompt(name)) ?? '';
  const { pairs } = await listPairs(name);

  const requested = opts.examples ?? DEFAULT_EXAMPLES;
  const exampleCount = Math.max(0, Math.min(requested, pairs.length));
  const examples = pairs.slice(0, exampleCount);
  const baseModel = opts.baseModel ?? model.spec.baseModel ?? DEFAULT_BASE;

  const lines: string[] = [];
  lines.push(`# Generated by c9ai for model project: ${model.spec.name}`);
  lines.push(`# Base: ${baseModel}`);
  lines.push(`# Few-shot examples: ${exampleCount} of ${pairs.length} pair(s)`);
  lines.push('');
  lines.push(`FROM ${baseModel}`);
  lines.push('');
  if (system.trim()) {
    lines.push(`SYSTEM """${escapeTriple(system.trim())}"""`);
    lines.push('');
  }
  for (const p of examples) {
    lines.push(`MESSAGE user """${escapeTriple(p.prompt)}"""`);
    lines.push(`MESSAGE assistant """${escapeTriple(p.completion)}"""`);
  }
  if (examples.length > 0) lines.push('');
  lines.push('PARAMETER temperature 0.7');
  lines.push('PARAMETER top_p 0.9');
  lines.push('');

  const buildDir = path.join(model.dir, 'build');
  await fs.mkdir(buildDir, { recursive: true });
  const modelfilePath = path.join(buildDir, 'Modelfile');
  await fs.writeFile(modelfilePath, lines.join('\n'), 'utf8');
  await fs.writeFile(
    path.join(buildDir, 'metadata.json'),
    JSON.stringify(
      {
        createdAt: new Date().toISOString(),
        model: model.spec.name,
        ollamaTag: model.spec.ollamaModel,
        baseModel,
        exampleCount,
        totalPairs: pairs.length,
        pairHash: await sha256File(path.join(model.dir, 'pairs', 'pairs.jsonl')),
        modelfilePath,
      },
      null,
      2
    ) + '\n',
    'utf8'
  );

  return {
    modelfilePath,
    buildDir,
    baseModel,
    exampleCount,
    totalPairs: pairs.length,
    systemPromptIncluded: system.trim().length > 0,
    ollamaTag: model.spec.ollamaModel,
    createCommand: `ollama create ${model.spec.ollamaModel} -f "${modelfilePath}"`,
  };
}

export interface OllamaCreateResult {
  exitCode: number;
}

export async function runOllamaCreate(
  tag: string,
  modelfilePath: string,
  onLine: (line: string) => void
): Promise<OllamaCreateResult> {
  return new Promise(resolve => {
    let child;
    try {
      child = spawn('ollama', ['create', tag, '-f', modelfilePath], {
        stdio: ['ignore', 'pipe', 'pipe'],
      });
    } catch (err) {
      onLine(`error: ${err instanceof Error ? err.message : String(err)}`);
      resolve({ exitCode: 1 });
      return;
    }

    let buffer = '';
    const flushLines = (chunk: Buffer) => {
      buffer += chunk.toString();
      let nl: number;
      while ((nl = buffer.indexOf('\n')) >= 0) {
        const line = buffer.slice(0, nl).replace(/\r$/, '');
        buffer = buffer.slice(nl + 1);
        if (line.trim()) onLine(line);
      }
    };

    child.stdout?.on('data', flushLines);
    child.stderr?.on('data', flushLines);
    child.on('error', err => {
      onLine(`error: ${err.message}`);
      resolve({ exitCode: 1 });
    });
    child.on('close', code => {
      const tail = buffer.replace(/\r/g, '').trim();
      if (tail) onLine(tail);
      resolve({ exitCode: code ?? 0 });
    });
  });
}
